### ISSUE TITLE
Github installation, checking for dependencies - error output

### ISSUE THREAD

**Issue by jade-davies** [HRGV/phyloFlash#114]
Hello,

I am installing phyloFlash from github using the code specified:

`wget https://github.com/HRGV/phyloFlash/archive/pf3.3b3.tar.gz`
`tar -xzf pf3.3b3.tar.gz`

And then check for dependencies using:

`cd phyloFlash-pf3.3b3`
`./phyloFlash.pl` `-check_env`

And the output received is as below:

`Can't locate Time/Piece.pm in @INC (@INC contains: /qib/research-groups/Arjan-Narbad/shared_tools/phyloFlash-pf3.3b3 /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /qib/research-groups/Arjan-Narbad/shared_tools/phyloFlash-pf3.3b3/PhyloFlash.pm line 6.
BEGIN failed--compilation aborted at /qib/research-groups/Arjan-Narbad/shared_tools/phyloFlash-pf3.3b3/PhyloFlash.pm line 6.
Compilation failed in require at ./phyloFlash.pl line 291.
BEGIN failed--compilation aborted at ./phyloFlash.pl line 291.`

What does this mean? Thanks!

**Comment by kbseah** [comment]
Hello @jade-davies ,
The script requires the Perl module Time::Piece. This should be among the [Perl core modules](https://perldoc.perl.org/index-modules-T.html), but perhaps your Perl version is too old or too new (modules are sometimes added to or removed from the core modules). What is your Perl version? (run `perl -version` to check)

The easiest way to install phyloFlash is via Conda. Details for phyloFlash are [here](https://hrgv.github.io/phyloFlash/install.html), and more information on Conda [here](https://docs.conda.io/projects/conda/en/latest/). 

One last thing; if you are not using single-end read data, please use version v3.3b2 when installing via Conda. There was a bug in v3.3b3 that was fixed with version v3.3b4 but there is a delay in updating the recipe on Conda.

**Comment by jade-davies** [comment]
Hi @kbseah,

Thank you for the quick reply and helpful information! 

I am trying to install v3.3b2 via conda, but looking at the search results on https://anaconda.org/bioconda/phyloflash, I cannot see this version there. It looks like only v3.3b1 and v3.3b3 are available to install.

**Comment by kbseah** [comment]
The page only shows the latest version for each operating system. You can find a complete list of available package versions at the command line with the command:
```
conda search -c bioconda phyloflash
```

The parameter `-c bioconda` means "search the Bioconda channel only". 

To specify a specific version to install, use the equals sign as follows `phyloflash=3.3b2` (for example). 

Do refer to the phyloFlash manual for complete instructions on installation via Conda.

**Comment by jade-davies** [comment]
Thank you for your help, much appreciated!
