### ISSUE TITLE
-lib may contain only alphanumeric characters

### ISSUE THREAD

**Issue by susheelbhanu** [HRGV/phyloFlash#126]
Hi,

I'm trying to run PhyloFlash on my data via snakemake. In order to do that, I need to set the `-lib` parameter to a folder in a different path. It keeps failing and when I tried the command manually (shown below), it looks like I cannot provide a path for the `-lib` flag, and needs ONLY a folder name. 

```
phyloFlash.pl -dbhome /mnt/lscratch/users/sbusi/metaG_JULY_2020/IMP3/bins/138.1 -CPUs 24 -lib $(dirname /scratch/users/sbusi/metaG_JULY_2020/IMP3/bins/archaea/GL_R11_GL15_UP_1/phyloflash_output/GL_R11_GL15_UP_1.phyloFlash.html) -read1 /scratch/users/sbusi/metaG_JULY_2020/IMP3/bins/archaea/../../GL_R11_GL15_UP_1/run1/Preprocessing/mg.r1.trimmed.PhiX_filtered.fq -read2 /scratch/users/sbusi/metaG_JULY_2020/IMP3/bins/archaea/../../GL_R11_GL15_UP_1/run1/Preprocessing/mg.r2.trimmed.PhiX_filtered.fq

This is phyloFlash v3.3b3

[10:02:12] Using dbhome
           '/mnt/lscratch/users/sbusi/metaG_JULY_2020/IMP3/bins/138.1'

ERROR: Argument to -lib may contain only alphanumeric characters,'_' and '-'.

Usage:
    phyloFlash.pl [OPTIONS] -lib name -read1 <file> -read2 <file>

    phyloFlash.pl -help

    phyloFlash.pl -man

    phyloFlash.pl -check_env

srun: task 0: Exited with exit code 2
```

Is there a workaround for this?

Thank you,
Susheel

**Comment by kbseah** [comment]
Hello Susheel,

Sorry to hear about this, the decision to make the `-lib` option take only a filename prefix made sense at the time but sometimes causes problems like this. 

Check [here](https://hrgv.github.io/phyloFlash/FAQ.html) for an example Snakemake rule for phyloFlash. Do let us know if it works for you.

Best regards,
Brandon

**Comment by susheelbhanu** [comment]
Hey Brandon, 

Thanks a lot for the super-quick reply. Which `snakemake` version were you using for this? Using the model you sent me, I'm getting an error that the output, logs, and benchmark files do not have the same wildcards. 

-Susheel

**Comment by kbseah** [comment]
Hello Susheel,

I'm using Snakemake 5.5.0. Unfortunately I can't really help with Snakemake because constructing rules is tricky and depends often on what exactly the files are named and how Snakemake tries to parse them.

Also do note that in the rule you posted, the output field says that a file called "{full_sample}_phyloflash_output" should be created, but the shell command produces no such file. If you use the `-zip`, `-almosteverything` or `-everything` options of phyloFlash then a tar.gz archive with the suffix `.phyloFlash.tar.gz` will be produced, as shown in the FAQ example.

Hope that this helps
-Brandon

**Comment by susheelbhanu** [comment]
Thanks Brandon. I may have a workaround. Will let you know if it works!
