### ISSUE TITLE
Fasta input causes spades assembly failure

### ISSUE THREAD

**Issue by CormacKinsella** [HRGV/phyloFlash#97]
Hi there,

Thanks for the fantastic tool.

I am working with a metagenomic dataset where I no longer have access to the original fastqs, only high quality curated fasta files. 
This causes a bug with the SPAdes assembly step, which defaults to read error correction. 
adding the '--only-assembler' flag to the SPAdes sub command solves this issue for me and I get good assembly results.

I wonder whether it would be possible to add an option to define input as either fastq or fasta, with a different SPAdes behaviour depending on which is selected?

thanks,
Cormac

**Comment by kbseah** [comment]
Hello Cormac,

Thanks for the report. I don't think we're going to implement a Fasta input option any time soon, as very few users are using it in that way. However it might be a good idea to allow the user to pass additional options to the component programs. We'll keep this in view, but realistically we won't be implementing any changes in the immediate future because of other commitments. 

Best regards,
Brandon

**Comment by CormacKinsella** [comment]
Hi Brandon,

Sounds reasonable!

cheers,
Cormac
